import streamlit as st
import os

os.makedirs("./video", exist_ok=True)
os.makedirs("./output", exist_ok=True)

input_video = "./video/IMG_0385.MP4"
analysed_video = "./output/analysis.mp4"
output_video = "./output/output.mp4"

from bikefit.analysis import run_keypoint_on_video
from bikefit.video_utils import convert_video_for_streamlit, print_result

st.markdown("# Bike Fit Checker App")

st.markdown("## Get started")
st.markdown("Upload a video to get started. The video will be analyzed and a report will be generated.")
st.markdown("The video should be in a .mp4 format with at least 30 fps.")
uploaded_file = st.file_uploader("Upload a video", type="mp4", accept_multiple_files=False)

if uploaded_file is not None:
    with open(input_video, "wb") as file:
        file.write(uploaded_file.getbuffer())


    st.write("Video is being processed, please wait...")

    measure_angles = run_keypoint_on_video(input_video, analysed_video)


    if measure_angles is None:
        st.error("Issue with video analytics")

    print_result(measure_angles)

    conv = False
    if os.path.exists(analysed_video):
        conv = convert_video_for_streamlit(analysed_video, output_video)
    else:
        st.error("Issue with video ouput")

    if conv:
        st.write("Video generated by the model :")
        st.video(output_video)
    else:
        st.error("Issue with video conversion")